name: F1 Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Installation
      run: make setup

    - name: Linting
      run: make lint

    - name: Testing
      run: make test
